config/routes.rb
Rails.application.routes.draw do
  devise_for :merchants, :controllers => { :registrations => 'registrations'}
  
  resources :merchants do
    resources :shops
    resources :photos
  end
  resources :shops do
    resources :items
    resources :photos
  end

  resources :items do
  	resources :photos
  end
  
  root to: 'items#index'
  match "*path" => "items#index", via: [:get, :post]  
end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  url         :string(255)
#  merchant_id :integer
#  address     :text
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Shop < ActiveRecord::Base
	has_many :photos, as: :imageable
	has_many :items
	belongs_to :merchant
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	before_action :authenticate_merchant!, only: [:update, :create, :new, :edit, :destroy]
	before_action :get_shop, only: [:show, :update, :destroy, :edit]

	def get_shop
		@shop = Shop.find(params[:id])
	end

	def index
		@shops = Shop.all
	end

	def show

	end

	def edit

	end

	def new
		redirect_to shop_items_path(current_merchant) unless current_merchant.shops.length == 0
		@shop = Shop.new
		@shop.merchant_id = params[:merchant_id]
		flash[:notice] = params
	end

	def create
		@shop = Shop.new(shop_params)
		if @shop.save
			flash[:success] = "Shop created succesfully"
			redirect_to new_shop_item_path(@shop)
		else
			flash[:danger] = "Couldn't create shop #{@shop.errors.full_messages}"
			redirect_to new_shop_item_path(@shop)
		end
	end

	def update
		if @shop.update_attributes(shop_params)
			flash[:success] = "Shop updated succesfully"
			redirect_to new_shop_item_path(@shop)
		else
			flash[:danger] = "Couldn't update shop #{@shop.errors.full_messages}"
			render 'edit'
		end
	end

	def destroy
		@shop.destroy
		redirect_to shops_path
	end

	private

	def shop_params
		params.require(:shop).permit!
	end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<div class="container-fluid">
  <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-1 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <% if @shop.new_record? %>
            <h3 class="panel-title">Please add your shop to Vintage.ie <small>It's free!</small></h3>
          <% else %>
            <h3 class='panel-title'>Update your shop<small>It's free!</small></h3>
          <% end %>
          
        </div>
          <div class="panel-body">

              <%= form_for @shop , html: { role: 'form'} do |f|%>
                <div class="col-xs-11 col-sm-11 col-md-11">
                  <div class="form-group">
                      <%= f.text_field :name, class: "form-control input-sm", :placeholder => 'Shop Name' %>
                  </div>
                </div>
                <div class="col-xs-11 col-sm-11 col-md-11">
                  <div class="form-group">
                      <%= f.text_area :address, class: "form-control input-sm", :placeholder => 'Address' %>
                  </div>
                </div>
                <div class="col-xs-11 col-sm-11 col-md-11">
                  <div class="form-group">
                      <%= f.text_field :url, class: "form-control input-sm", :placeholder => 'www.etc.com' %>
                  </div>
                </div>   
                <div class="col-xs-11 col-sm-11 col-md-11">
                  <div class="form-group">
                      <%= f.text_area :description, class: "form-control input-sm", :placeholder => 'Describe your shop' %>
                  </div>
                </div>
                <%= f.hidden_field :merchant_id, value: @shop.merchant_id %>               
                <%= f.submit class: 'btn btn-primary shop-signup-submit' %>
              <% end %>

          </div>
            </div>
          </div>
      </div>
</div>

app/views/shops/index.html.erb
<% @shops.each do |shop| %>
	<%= link_to shop.name, shop %>
<% end %>

<% if @shops.empty? %>
	<%= link_to 'Create a shop', new_merchant_shop_path(current_merchant.id) %>
<% end %>

app/views/shops/show.html.erb
<%= @shop.name %>