config/routes.rb
Rails.application.routes.draw do
  devise_for :merchants, :controllers => { :registrations => 'registrations'}
  
  resources :merchants do
    resources :shops
    resources :photos
  end
  resources :shops do
    resources :items
    resources :photos
  end

  resources :items do
  	resources :photos
  end
  
  root to: 'items#index'
  match "*path" => "items#index", via: [:get, :post]  
end

app/views/partials/_left.html.erb
<% 3.times.each do |i| %>
	<div class="row">
	  <div class="center-block">
	    <a href="#" class="thumbnail">
	      <img data-src="holder.js/300x150" class="img-circle img-responsive">
	    </a>
	  </div>
	  
	</div>


<% end %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% if current_merchant %>
        	<li ><%= link_to current_merchant.first_name, merchant_path(current_merchant) %></li>
        
          <% if (current_merchant.shops != [])  %>
            <li><%= link_to current_merchant.shops.first.name, shop_items_path(current_merchant.shops.first) %></a></li>
          <% end %>
        <% end %>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">Link</a></li> -->
        <% if current_merchant %>
          <li><%= link_to 'Logout', destroy_merchant_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_merchant_session_path %></li>
        <% end %>
        <li><%= link_to 'All items', items_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>