config/routes.rb
Rails.application.routes.draw do
  devise_for :merchants, :controllers => { :registrations => 'registrations'}
  
  resources :merchants do
    resources :shops
    resources :photos
  end
  resources :shops do
    resources :items
    resources :photos
  end

  resources :items do
  	resources :photos
  end
  
  root to: 'items#index'
  match "*path" => "items#index", via: [:get, :post]  
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  price       :decimal(8, 2)
#  description :text
#  name        :string(255)
#  size        :float
#  created_at  :datetime
#  updated_at  :datetime
#

class Item < ActiveRecord::Base
	has_many :photos, as: :imageable
	belongs_to :shop
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_merchant!, only: [:update, :create, :new, :edit, :destroy]
	before_action :correct_merchant?, only: [:update, :edit, :create, :new, :destroy]

	def correct_merchant?
		redirect_to shop_items_path(params[:shop_id]) unless current_merchant == Shop.find(params[:shop_id]).merchant
	end

	def index
		if params[:shop_id]
			@params = params
			@shop = Shop.find(params[:shop_id])
			@items = @shop.items
			@shop_items_photos = []
			@items.each do |item|
				item.photos.each do |photo|
					photos << photo
				end
			end
			@shop_items_photos
		else
			@shop_items_photos = Photo.all.where(imageable_type: 'Item')
			@items = Item.all
		end
	end

	def show
		@params = params
		@item = Item.find(params[:id])
		@photos = @item.photos
	end

	def edit
		@shop = Shop.find(params[:shop_id])
		@item = Item.find(params[:id])
		@context = Shop.find(params[:shop_id])
		@photos = @item.photos.all
		@photo = @item.photos.new
		flash[:notice] = params
	end

	def new
		@context = Shop.find(params[:shop_id])
		@item = @context.items.new
		@photo = @context.photos.new
		flash[:notice] = params
		@photos = @context.photos.all
		
		
	end

	def create
		@item = Item.new(item_params)
		@shop = Shop.find(item_params[:shop_id])
		if @item.save
			flash[:success] = 'Item created succesfully'
			redirect_to edit_shop_item_path(@shop, @item)
		else
			flash[:danger] = "Couldn't create item #{@item.errors.full_messages}"
			render 'new'
		end
	end

	def update
		@item = Item.find(params[:id])
		@shop = Shop.find(item_params[:shop_id])
		if @item.update_attributes(item_params)
			flash[:success] = "Item updated succesfully"
			redirect_to edit_shop_item_path(@shop, @item)
		else
			flash[:danger] = "Couldn't update item #{@item.errors.full_messages}"
			render 'edit'
		end
	end

	def destroy
		@item.destroy
		redirect_to shop_items_path
	end

	private

	def item_params
		params.require(:item).permit!
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="container-fluid">   
  <div class="col-md-6 photo_placholder">     
    <%= form_for [@item, @photo], remote: true, :html => {id:"my-awesome-dropzone", class:'dropzone' } do |f| %>
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group fallback">
               <%= f.file_field :photo %>
          </div>
        </div>
        
        <div class="dz-message " data-dz-message>
          <span class="col-xs-5 col-sm-5 col-md-5">Drag files or click here</span></div>
        <div class="fallback">                       
        </div> 
        
    <% end %>        
    
                      
    </div> <!-- end of col-md4 -->   
    <div class="col-md-1"><button id="edit_form_save_button" class='btn btn-success'>Upload</button></div>
    <div class="col-md-4 pull-right">
      <div class="panel panel-default">
        <div class="panel-heading">
          <% if @item.new_record? %>
            <h3 class="panel-title">Add an item to your store <small>It's free!</small></h3>
          <% else %>
            <h3 class='panel-title'>Update your item<small>It's free!</small></h3>
          <% end %>
        </div>
        <div class="panel-body">
          <%= form_for [@context, @item], html: { id: 'item_edit' } do |f| %>
              
            <div class="col-xs-11 col-sm-11 col-md-11">
              <div class="form-group">
                  <%= f.text_field :name, class: "form-control input-sm", :placeholder => 'Item Name' %>
              </div>
            </div>
            <div class="col-xs-11 col-sm-11 col-md-11">
              <div class="form-group">
                  Size: <%= f.select :size, (4..32).step(0.5).to_a %>
              </div>
            </div>                
            <div class="col-xs-11 col-sm-11 col-md-11">
              <div class="form-group">
                  <%= f.text_area :description, class: "form-control input-sm", :placeholder => 'Description of your item' %>
              </div>
            </div>
            <div class="col-xs-11 col-sm-11 col-md-11">
              <div class="form-group">
                  <%= f.number_field :price, class: "form-control input-sm", :placeholder => 'How much?' %>
              </div>
            </div>
            <%= f.hidden_field :shop_id, value: @context.id %>
            
            <%= f.submit  class: 'btn btn-primary shop-signup-submit' %>
          <% end %>
          
        </div>
      </div>
    </div>  


  </div> <!-- end of row container -->
<div class="container">
  <div class="row ">
  <div class="col-md-2"></div>
  <div class="col-md-2 preview_photo"></div>

</div>
  <div class="row">      
    <% if !@photos.empty? %>
      <%= render @photos %>
    <% end %>    
  </div> <!-- end of row -->
</div>
    
      
            

app/views/items/_new_form.html.erb
<div class="container-fluid">
	<div class="row centered-form">
	  <div class="col-md-4 col-md-offset-4">
	  	<div class="panel panel-default">
	      <div class="panel-heading">
	        <% if @item.new_record? %>
	          <h3 class="panel-title">Add an item to your store <small>It's free!</small></h3>
	        <% else %>
	          <h3 class='panel-title'>Update your item<small>It's free!</small></h3>
	        <% end %>
	      </div>
	      <div class="panel-body">
	        <%= form_for [@context, @item], html: { id: 'item_edit' } do |f| %>
	            
	          <div class="col-xs-11 col-sm-11 col-md-11">
	            <div class="form-group">
	                <%= f.text_field :name, class: "form-control input-sm", :placeholder => 'Item Name' %>
	            </div>
	          </div>
	          <div class="col-xs-11 col-sm-11 col-md-11">
	            <div class="form-group">
	                Size: <%= f.select :size, (4..32).step(0.5).to_a %>
	            </div>
	          </div>                
	          <div class="col-xs-11 col-sm-11 col-md-11">
	            <div class="form-group">
	                <%= f.text_area :description, class: "form-control input-sm", :placeholder => 'Description of your item' %>
	            </div>
	          </div>
	          <div class="col-xs-11 col-sm-11 col-md-11">
	            <div class="form-group">
	                <%= f.number_field :price, class: "form-control input-sm", :placeholder => 'How much?' %>
	            </div>
	          </div>
	          <%= f.hidden_field :shop_id, value: @context.id %>
	          
	          <%= f.submit  class: 'btn btn-primary shop-signup-submit' %>
	        <% end %>	        
	      </div>
	    </div>
	  </div>
  </div>
</div>

app/views/items/_photo.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    
    <a href="<%= photo.photo.url %>" data-lightbox="image-1" data-title="<%= photo.photo %>"><%= image_tag photo.photo, size: "150x150", class: "img-responsive" %></a>
    <div class="caption">
      <h3>Thumbnail label</h3>
      <p><%= link_to 'View item', item_path(photo.imageable), class: 'btn btn-info' %></p>
      <!-- <p><a href="#" class="btn btn-primary" role="button">Button</a> </p> -->
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<%= @params %> <br>

<% @items.each do |item| %>
	<%= item.name %><br>
<% end %> 

<div class="row">
	
	<div class="col-md-6 col-md-offset-3">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    	<% @shop_items_photos.count.times do |i| %>
					<% if i == 0 %>
						<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<% else %>
						<li data-target="#carousel-example-generic" data-slide-to="<%= i %>"></li>
					<% end %>
				<% end %>
	    
	  </ol>

	  <!-- Wrapper for slides -->
		  <div class="carousel-inner">
	    	<% @shop_items_photos.each_with_index do |photo, index| %>
					<div class="item <% if index == 0 %>active<% end %>">
						<%= image_tag photo.photo %>
						<div class="carousel-caption">
							..
						</div>
					</div>
				<% end %>	   
		  </div> <!-- end of carousel-inner -->
	  

	  	<!-- Controls -->
		  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left"></span>
		  </a>
		  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right"></span>
		  </a>
		</div> <!-- end of carousel-example-generic -->
	</div> <!-- end of col-md-6 -->
</div> <!-- end of row -->
<div class="row">
	<div class="col-md-12">
		<%= render partial: 'photo', collection: @shop_items_photos %>
	</div>
</div>

app/views/items/new.html.erb
<%= render 'new_form' %>

app/views/items/show.html.erb
<%= @params %><br>
<%= @item.name %>

<!-- renders photos/photo partial -->
<div class="container-fluid">
	<%= render @photos %>
</div>